# Cassandra Connector - Real-time data (hot storage)
# Query: SELECT * FROM cassandra.playback.continue_watching

connector.name=cassandra
cassandra.contact-points=playback-cassandra
cassandra.native-protocol-port=9042
cassandra.load-policy.dc-aware.local-dc=datacenter1
cassandra.consistency-level=LOCAL_ONE
cassandra.allow-drop-table=false
